### ISSUE TITLE
Suggestion: Bedrock-compatible 2-shelf option

### ISSUE THREAD

**Issue by Brickgard** [LOOHP/Bookshelf#5]
Bedrock players (via GeyserMC, for example) only have 3 and 6 row containers available.
The "classic" 2 rows of inventory for a bookshelf inventory is awesome, but looks a bit ugly for a Bedrock user.
However, if the middle row of a 3-row container box was unusable (such as having oak planks that cannot be interacted with), the shelves would look nicer for Bedrock players while still only having 2 rows available.

Example: `config.yml`
```
Options:
  BookShelfRows: 2
  
  # If this is true, BookShelfRows is set to 3 with a "dead row" in the middle for better Bedrock compatibility.
  BedrockCompatible: true
```

This is definitely a minor QoL update, simply cosmetic, but may also serve as a nice "selling point" that the plugin has a "Bedrock compatible" appearance/feature.  Figured I'd suggest it, since this plugin's really great and I'd love to see it look even nicer for *all* of my players.

Thanks for your consideration and awesome resource!
